plugins {
    id 'base'
}

subprojects {
    group = 'de.jeff_media'
    version = properties['mod_version'] ?: '2.2.0'

    repositories {
        mavenCentral()
    }
    
    // Common settings
    tasks.withType(JavaCompile).configureEach {
        options.release.set(21)
        options.encoding = 'UTF-8'
    }

    // Output all jar tasks (including sources, dev, shadow) to the root directory
    tasks.withType(Jar).configureEach {
        destinationDirectory.set(file("$rootDir/build/libs"))
    }
}
