# Gradle Properties
org.gradle.jvmargs=-Xmx1G
org.gradle.java.home=C:/Program Files/Java/jdk-25.0.2


# Mod Properties
mod_version=2.3.0
maven_group=de.jeff_media.doorsreloaded
archives_base_name=DoorsReloaded

# Fabric Properties
minecraft_version=26.1.2
loader_version=0.19.2

# Dependencies
fabric_version=0.150.0+26.1.2
paper_api_version=26.1.2.build.66-stable
