gradle.properties
# Gradle Properties
org.gradle.jvmargs=-Xmx1G
org.gradle.java.home=C:/Program Files/Java/jdk-25.0.2


# Mod Properties
mod_version=2.2.0
maven_group=de.jeff_media.doorsreloaded
archives_base_name=DoorsReloaded

# Fabric Properties
# Fabric Properties
minecraft_version=26.1.1
# Note: Yarn/Fabric API versions for 1.21.11 might need adjustment if they don't follow this exact pattern
yarn_mappings=26.1.1+build.1
loader_version=0.18.1

# Dependencies
fabric_version=0.139.5+1.21.11
