plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

base {
    archivesName = "DoorsReloaded-${project.version}-Paper"
}

tasks.withType(Jar).configureEach {
    archiveVersion.set("")
}

repositories {
    mavenCentral()
    maven { url "https://repo.papermc.io/repository/maven-public/" }
}

dependencies {
    compileOnly "io.papermc.paper:paper-api:${project.paper_api_version}"
}

processResources {
    def props = [
        project: [
            name: 'DoorsReloaded',
            version: project.version
        ],
        plugin: [
            main: 'de.jeff_media.doorsreloaded.Main',
            prefix: 'DoorsReloaded'
        ]
    ]
    inputs.properties props
    filesMatching('plugin.yml') { expand props }
}

shadowJar {
    archiveClassifier = ''
}
